### ISSUE TITLE
CRUD de Plano de Sócio

### ISSUE THREAD

**Issue by raphaelaferraz** [EquipeTantera/Landing_Page_Tantera#146]
### Descrição:

Item que deve ser realizado por apenas uma pessoa, de modo a construir o CRUD sobre os planos de sócios que serão apresentados na lading page.

### Metas:

- Seguir fielmente as informações que serão apresentadas na lading page
- Permitir a Criação, Deleção, Atualização e Edição do Plano de sócio

**Comment by AnaBarb0sa** [comment]
Foi criado:
- Tabela de planos: nome, preço, id de vantagem, id pagamentos, id de faq;
- Tabela de vantagem: nome e descrição;
- Tabela de pagamentos: nome e descrição;
- Tabela de Faq: pergunta e resposta.

Atualizações:
- Acessos ao crud de planos para diretorias especificas: Esportes e presidência.
