### ISSUE TITLE
Revisão de Relacionamentos entre as Entidades

### ISSUE THREAD

**Issue by raphaelaferraz** [EquipeTantera/Landing_Page_Tantera#156]
## Descrição:
Item que deve ser realizado com o objetivo de verificar se todos os relacionamentos estão corretos entre todas as entidades do banco de dados. 

>[!WARNING]
Ao realizar a revisão dos relacionamentos, sempre levar em conta a navegação das páginas que estão no Figma!

## Metas:
- Todos os relacionamentos entre as entidades estarem funcionando corretamente
- Todas as páginas e partes da lading page estarem corretamente representadas pelas entidades

**Comment by AnaBarb0sa** [comment]
@Anag0es - revisar:
- [ ] video;
- [ ] board;
- [ ] member;
- [ ] product;
- [ ] photo_product;
- [ ] category_product;
- [ ] category;
- [ ] plan;
- [ ] partner.


@ceciliagalvaoo - revisar:
- [ ] Event;
- [ ] photo;
- [ ] event_registration_card;
- [ ] event_form;
- [ ] course;
- [ ] class;
- [ ] year;
- [ ] banner.
