### ISSUE TITLE
Teste de Endpoints

### ISSUE THREAD

**Issue by raphaelaferraz** [EquipeTantera/Landing_Page_Tantera#158]
## Descrição:
Item que deve ser realizado com o objetivo de verificar o funcionamento de todos os endpoints do backend da lading page. 

>[!WARNING]
> Disponibilizar um Postman específico com os resultados desses testes :)

## Metas:
- Testar todos os endpoints do backend da lading page
- Bater os testes realizados com o fluxo de páginas que estão no Figma 
- Corrigir eventuais falhas que forem percebidas ao longo do teste

**Comment by AnaBarb0sa** [comment]
@Anag0es - Testar:
- [ ] video;
- [ ] board;
- [ ] member;
- [ ] product;
- [ ] photo_product;
- [ ] category_product;
- [ ] category;
- [ ] plan;
- [ ] partner.

---

@ceciliagalvaoo - Testar:
- [ ] Event;
- [ ] photo;
- [ ] event_registration_card;
- [ ] event_form;
- [ ] course;
- [ ] class;
- [ ] year;
- [ ] banner.
