### ISSUE TITLE
Refinamento de Conteúdos das Telas Desktop + Entendimento aprofundado dos mockups desenvolvidos

### ISSUE THREAD

**Issue by raphaelaferraz** [EquipeTantera/Landing_Page_Tantera#61]
### Descrição:

Item que deve ser realizado por apenas um integrante do time.

### Metas:

- Bianca entender profundamente o posicionamento dos conteúdos no mockup
- Bianca entender o quanto os conteúdos são importantes para uma página e se está faltando algum 
- Bianca sugerir possíveis alterações

**Comment by Biabborges** [comment]
https://docs.google.com/document/d/1Hm_CcDcJ1-uPGEwQSccGID_UO9dwpYqHEidqr9CTjxQ/edit?usp=sharing
